In [2]:
from PIL import Image
import tensorflow as tf
from tensorflow.keras.preprocessing import image_dataset_from_directory
import tensorflow_hub as hub

In [3]:
converted_img  = tf.image.convert_image_dtype(img, tf.float32)[tf.newaxis, ...]

NameError: name 'img' is not defined

In [4]:
directory = "test2017/test2017/"

In [5]:
image = tf.io.read_file("test2017/test2017/000000000001.jpg")

2022-06-20 22:33:40.553240: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:961] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-06-20 22:33:40.589571: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:961] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-06-20 22:33:40.590077: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:961] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2022-06-20 22:33:40.592515: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate

In [7]:
new_img = tf.image.decode_image(image, dtype=tf.float32)[tf.newaxis, ...]

In [8]:
module_handle = "https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1"
detector = hub.load(module_handle).signatures['default']

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


In [9]:
result = detector(new_img)

2022-06-20 22:34:06.418065: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 18524160 exceeds 10% of free system memory.
2022-06-20 22:34:06.809524: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 18524160 exceeds 10% of free system memory.
2022-06-20 22:34:09.021854: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 18524160 exceeds 10% of free system memory.
2022-06-20 22:34:09.242490: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 18524160 exceeds 10% of free system memory.
2022-06-20 22:34:13.175750: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
2022-06-20 22:34:15.616221: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-06-20 22:34:15.655904: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-06-20 22:34:15.657400: W tensorflow/stream_exe

In [10]:
result

{'detection_class_labels': <tf.Tensor: shape=(100,), dtype=int64, numpy=
 array([571, 571, 409, 391, 571, 391, 334, 535, 571, 391, 391, 391, 391,
        391, 391, 391, 571, 552, 391, 391, 334, 334, 391, 391, 571, 409,
        391, 391, 391, 571, 571, 334, 334, 409, 334, 334, 391, 391, 571,
        571, 334, 334, 571, 391, 391, 334, 334, 334, 334, 391, 571, 334,
        334, 409, 391, 571, 334, 334, 391, 391, 391, 391, 391, 409, 334,
        391, 571, 391, 334, 334, 400, 334, 334, 391, 409, 571, 391, 334,
        334, 334, 334, 334, 409, 334, 334, 571, 334, 571, 334, 391, 334,
        334, 571, 334, 391, 571, 409, 334, 391, 334])>,
 'detection_class_entities': <tf.Tensor: shape=(100,), dtype=string, numpy=
 array([b'Car', b'Car', b'Wheel', b'Tree', b'Car', b'Tree', b'Plant',
        b'Van', b'Car', b'Tree', b'Tree', b'Tree', b'Tree', b'Tree',
        b'Tree', b'Tree', b'Car', b'Tire', b'Tree', b'Tree', b'Plant',
        b'Plant', b'Tree', b'Tree', b'Car', b'Wheel', b'Tree', b'Tree',
  

: 